version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./.qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    env_file: .env
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
    entrypoint: ["bash", "-lc", "sleep infinity"]
    stdin_open: true
    tty: true

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - runs_data:/app/.runs
    working_dir: /app
    env_file: .env
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - PORT=8000
      - HOST=0.0.0.0
    command: ["bash", "cloud/start_web.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  runs_data:
