version: '3.8'

services:
  ai-dev-runpod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-dev-runpod
    restart: unless-stopped
    ports:
      - "8000:8000"   # HTTP (redirects to HTTPS)
      - "8443:8443"   # HTTPS
    environment:
      # RunPod Configuration
      - RUNPOD_MODE=true
      - HOST=127.0.0.1
      - PORT=8080
      - WORKERS=4
      
      # Uncensored Operation
      - UNCENSORED_MODE=true
      - DISABLE_CONTENT_FILTER=true
      - ALLOW_UNSAFE_CODE=true
      - BYPASS_SAFETY_CHECKS=true
      - DISABLE_MODERATION=true
      - SKIP_CONTENT_VALIDATION=true
      - ALLOW_ALL_REQUESTS=true
      
      # LLM Configuration
      - LLM_BACKEND=openai
      - MODEL_TEMPERATURE=0.9
      - MODEL_TOP_P=0.95
      - MODEL_MAX_TOKENS=4096
      - ENABLE_SYSTEM_PROMPTS=true
      
      # Vector Database
      - VECTOR_BACKEND=qdrant
      - QDRANT_URL=http://qdrant:6333
      
      # Performance
      - OMP_NUM_THREADS=4
      - TORCH_CUDA_ARCH_LIST=6.0;6.1;7.0;7.5;8.0;8.6
      
      # API Keys (set these in RunPod environment)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      
    volumes:
      - ai-dev-data:/app/data
      - ai-dev-runs:/app/.runs
      - ai-dev-logs:/app/logs
    
    # GPU support for RunPod
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8443/health", "--insecure"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai-dev-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

volumes:
  ai-dev-data:
    driver: local
  ai-dev-runs:
    driver: local
  ai-dev-logs:
    driver: local
  qdrant-data:
    driver: local

networks:
  default:
    driver: bridge
